### ISSUE TITLE
Resistance of parallel circuit

### ISSUE THREAD

**Issue by nukisman** [csicar/purescript-typelevel-measures#2]
Let consider parallel connection of electrical circuits.

```
type R = 
  Number : Ohm ()

resistance r =
  liftV r ** ohm
```

Resistance of parallel circuit could be evaluated in two ways:

### Use Inverted Resistance

1. `1/R = 1/R1 + 1/R2 + ...`
2. `R = 1 / (1/R)`

This gives **type error**:
```
sumOfInverted rs =
  (rs # map (\r ->
    (liftV 1.0) // r) # foldl (++) ((liftV 1.0) // (resistance 0.0)))
```

If we make `rs` static - it will compile successfully:
```
rs ::
  Array R
rs =
  [ resistance 3.0
  , resistance 2.0
  ]

sumOfInvertedRs =
  (rs # map (\r ->
    (liftV 1.0) // r) # foldl (++) ((liftV 1.0) // (resistance 0.0)))

resistanceOfRs =
  liftV 1.0 // sumOfInvertedOfRs
```
But anyway we use **division by zero**:
```
> sumOfInvertedRs
Infinity·A²kg⁻¹m⁻²s³
> resistanceOfRs
0.0·A⁻²kg¹m²s⁻³
```

### Evaluate Direct Resistance

We also could use formula `R = (R1 * ... * Rn) / ( (R1 * ... * Rn / R1) + ... + (R1 * ... * Rn / Rn))`. Eg.: 
* `R = R1 * R2 / (R1 + R2)`
* `R = R1*R2*R3 / (R2*R3 + R1*R3 + R1*R2)`

It works for static number of arguments, but not for `Array`: `(**)` could not be folded. It gives **type error**.
```
productOf rs =
  rs # foldl (**) (resistance 1.0)
```
**Question 1**: Is possible to fold `(**)` in some way?
**Question 2**: Could you suggest a solution for this problem (in case of `Array R` as input)?

**Comment by nukisman** [comment]
I had found solution via avoiding division by zero: fold `++` for **non-empty array**

```
type InvertedResistance
  = Measured Number 
    ( ampere :: MeasureExp AmpereT (Pos (Succ (Succ Z)))
    , kg :: MeasureExp KgT (Neg (Succ Z))
    , meter :: MeasureExp MeterT (Neg (Succ (Succ Z)))
    , sec :: MeasureExp SecT (Pos (Succ (Succ (Succ Z))))
    )

sumOfInvertedRs ::
  R ->
  Array R -> 
  InvertedResistance
sumOfInvertedRs r0 rs =
  (rs # map (\r ->
  (liftV 1.0) // r) # foldl (++) ((liftV 1.0) // r0))

resistanceN :: R -> Array R -> R
resistanceN r0 rs =
  liftV 1.0 // (sumOfInvertedRs r0 rs)
```

**Comment by csicar** [comment]
Took me a while, but I found the solution:

when using `foldl` in this case you want to use the neutral element of (++) as the starting value.
We both assumed that the neutral element would be `1 / (0 Ω)` when in fact the unit is `1 / Ω` and the value is `0` meaning the neutral element for adding values with unit `1 / Ω` is `0* 1/Ω`. For short the neutral element is `0 / Ω`

The working code looks like this:
```purescript
sumOfInverted' ::
  Array (Number : Ohm ()) -> Number : Ampere P2 * Kg N1 * Meter N2 * Sec P3 ()
sumOfInverted' rs =
  rs
    # map (\r -> liftV 1.0 // r)
    # foldl (++) (liftV 0.0 // ohm)
```

**Comment by csicar** [comment]
to answer your question:

#### Is possible to fold (**) in some way?

The reason is actually quite interesting:
The problem is, that multiplying two resistances changes the type: 1Ω * 1Ω = 1Ω² in math and `resistance 1 ** resistance 1 = liftV 1 ** ohm ** ohm` in PS. 

The means that you would expect `productOf [resistance 3] ` to have type `:: Int : Ohm ()`.
But `productOf [resistance 2, resistance 4]` should have type `:: Int : Ohm² ()`

In this case the *type depends on the value*, which purescript cannot handle.

#### Why does the version with a fixed number of arguments work?

In that case PureScript knows the type, as multiplying 3 resistances will *always* have type Ohm³. Regardless of the *values* that are multiplied. 

#### But why is the formula `R = R1*R2*R3 / (R2*R3 + R1*R3 + R1*R2)` correct?
The reason the product has type `Ohm` is that the same number of array elements are multiplied in the dividend and the divisor. 

#### Is there a solution for multiplying arrays?
I think there is. For PureScript to know the type of the product it needs to know the size of the array at type level, which can be done by adding a phantom type argument:

```purescript
data SizedArray a (size :: Nat) = SizedArray (Array a)
```

when calculating the product of such a SizedArray with Measured elements we can use that additional type information (I simplified the following definition by using Meter instead of Ohm):
```purescript
productOf :: SizedArray (Number : Meter P1 ()) size -> Number : Meter size ()
productOf = ....
```

### What about unitless Measures?

There is one special case, where multiplying two `Measured` values does *not* change the type: namely values with unit `()` (e.g. unitless measures). These values of this type can be multiplied indefinitely without changing the type. Consequently, `productOf` can be defined for this special case (the following compiles):
```purescript
productOf :: Array (Number : ()) -> Number : ()
productOf rs = rs # foldl (**) (liftV 1.0)
```

**Comment by nukisman** [comment]
@csicar thanks for your answer!
> to answer your question:
> 
> #### Is possible to fold (**) in some way?
> The reason is actually quite interesting:
> The problem is, that multiplying two resistances changes the type: 1Ω * 1Ω = 1Ω² in math and `resistance 1 ** resistance 1 = liftV 1 ** ohm ** ohm` in PS.
> 
> The means that you would expect `productOf [resistance 3] ` to have type `:: Int : Ohm ()`.
> But `productOf [resistance 2, resistance 4]` should have type `:: Int : Ohm² ()`
> 
> In this case the _type depends on the value_, which purescript cannot handle.
> #### Why does the version with a fixed number of arguments work?
> In that case PureScript knows the type, as multiplying 3 resistances will _always_ have type Ohm³. Regardless of the _values_ that are multiplied.

Yes, I see why it happening. But don`t know how to handle with it :-) 

> #### But why is the formula `R = R1*R2*R3 / (R2*R3 + R1*R3 + R1*R2)` correct?
I just try to infer it from source relation `1/R = 1/R1 + ... + 1/Rn`:
* n = 2:
  * `1/R = 1/R1 + 1/R2` - multiply both sides by `R1*R2`
  * `R1*R2 / R = R2 + R1` - divide both sides by `R1*R2`
  * `1/R = (R2 + R1) / R1*R2` - multiply both sides by `R * (R1 * R2) / (R2 + R1)`
  * `(R1 * R2) / (R2 + R1) = R`
  * `R = R1*R2 / (R1 + R2)`
* n = 3
  * `1/R = 1/R1 + 1/R2 + 1/R3`
  * `1/R = (R2*R3 + R1*R3 + R1*R2) / R1*R2*R3`
  * `R = R1*R2*R3 / (R2*R3 + R1*R3 + R1*R2)`
* ...
> ```purescript
> productOf :: SizedArray (Number : Meter P1 ()) size -> Number : Meter size ()
> productOf = ....
> ```
> 
Interesting! It is like dependent type!
> ### What about unitless Measures?
> ...
1. It unsafe, because in this case the programmer should control units with exponents.
2. But if have not other way: if I have an `Array (Number : Ohm ())` how could convert it to `Array (Number : ())`?

**Comment by csicar** [comment]
I think for your use-case the solution in https://github.com/csicar/purescript-typelevel-measures/issues/2#issuecomment-518598263 should be sufficient.

> 1. It unsafe, because in this case the programmer should control units with exponents.

The trick is to hide the constructor `SizedArray` to the library users and only expose only type-safe functions. An example can be found here: https://pursuit.purescript.org/packages/purescript-sized-vectors/

> 2. But if have not other way: if I have an Array (Number : Ohm ()) how could convert it to Array (Number : ())?

Besides the type-safe solution provided in https://github.com/csicar/purescript-typelevel-measures/issues/2#issuecomment-518598263, you can always resort to *unsafe* type coersion:
```purescript
changeUnitUnsafe :: forall a b. Number : a -> Number : b
changeUnitUnsafe = unsafeCoerce

unsafeMakeResistance :: Array (Number :  ()) -> Array (Number : Ohm ())
unsafeMakeResistance = map changeUnitUnsafe
```
